name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: ["MRaihanZ","yogaardiansyah"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: title
    attributes:
      label: Title
      description: A clear and concise title for the bug
      placeholder: e.g., Bug in user login
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened...
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please list the steps needed to reproduce the bug
      placeholder: e.g., Step 1, Step 2, Step 3...
  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen
      placeholder: What did you expect to happen?
